left:
- name: LÃ¦rling dokumentasjon
  url: /blog/apprentice
  weight: 1
main:
- name: Blogg
  url: /no/blog
  weight: 10
- name: Om websiden
  url: /no/about
  weight: 3
- name: IT1 vgs
  url: /old/it1
  weight: 2
- name: Min ydmyke hjemmeside
  url: https://sivert.pw
  weight: 1